name: test

on: 
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: check out
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: go build ./...
        working-directory: ./workspace

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: go test ./... -v
        working-directory: ./workspace

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./workspace
